// <auto-generated />
using System;
using CreditService.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CreditService.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251130162141_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CreditService.Api.Models.CreditApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Angsuran")
                        .HasColumnType("numeric")
                        .HasColumnName("angsuran");

                    b.Property<decimal>("Bunga")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bunga");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Plafon")
                        .HasColumnType("numeric")
                        .HasColumnName("plafon");

                    b.Property<int>("Tenor")
                        .HasColumnType("integer")
                        .HasColumnName("tenor");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Plafon")
                        .HasDatabaseName("idx_pengajuan_plafon");

                    b.HasIndex("Tenor")
                        .HasDatabaseName("idx_pengajuan_tenor");

                    b.ToTable("pengajuan_kredit", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
